name: https://docs.google.com/spreadsheets/d/e/2PACX-1vSX_bFaT1mjMk4R4Sds1ipKxqe5icsUVw2UuozKjowJbAHdz_AmbR5qWoQwwkNpUKOCL7EOBV2z7Tap/pub?output=csv

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Download CSV
        run: |
          curl -L "LINK_CSV_GOOGLE_SHEETS" -o data.csv

      - name: Commit changes
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"

          git add data.csv
          git commit -m "Auto update spreadsheet" || echo "No changes"

          git push
